FROM node:23-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json .

COPY pnpm-lock.yaml .

RUN pnpm install --frozen-lockfile

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN pnpm i -g serve

COPY . .

RUN pnpm run build

EXPOSE 5173

CMD ["serve", "-d", "dist", "-l", "5173"]
