app:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: nestjs-app
  ports:
    - '3000:3000'
  environment:
    - MONGO_URI=mongodb://mongo:27017/reeTest
  depends_on:
    - mongo
  networks:
    - app-network
  entrypoint: >
    sh -c "
    until nc -z mongo 27017; do
      echo 'Waiting for MongoDB...';
      sleep 2;
    done;
    npm run start:prod"
